//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Level1"",
            ""id"": ""ec7cc416-a40d-4862-8879-076d16c6e3b8"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""a2ccea3b-a09d-41bf-bb51-2b98ed183cfb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Collect"",
                    ""type"": ""Button"",
                    ""id"": ""69d65066-02d1-41e0-98eb-213a6db18dd7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""c68ec640-6577-4b46-8724-b1b71c8bb772"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cc96baba-8989-41d8-8768-6d64b082861d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""81e8ae73-3aa2-4365-9214-cd99eb0fcd2c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""21b059eb-d4a4-49ae-945a-3fcfda07abf0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0ef63348-f1a0-409d-879e-47f482895f48"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""15c238b3-1ee3-4a3b-8c83-5aa7e503c845"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""18e8bb5d-bfba-4515-ac9b-14cf50acdcf8"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dcac5030-8d44-4af3-a139-ffa6380667ae"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a0338f6c-3088-4697-8775-308001ab1860"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ced7a663-2c29-4224-a548-d8297590f9a3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d0217aca-8838-49a2-869e-9c9e2c591746"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Collect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Level2"",
            ""id"": ""d83fcdbb-705e-43b2-956f-c8c3a1c8358a"",
            ""actions"": [
                {
                    ""name"": ""Num0"",
                    ""type"": ""Button"",
                    ""id"": ""a5291399-011b-4486-af82-a1f5a1d436ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num1"",
                    ""type"": ""Button"",
                    ""id"": ""16dbeefd-6e86-4bb7-ba34-6148a3df48b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num2"",
                    ""type"": ""Button"",
                    ""id"": ""358f7b6c-a429-41e5-8e6c-5b8daeaef2a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num3"",
                    ""type"": ""Button"",
                    ""id"": ""77f87200-c6d4-4bc6-9eb8-445499054f7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num4"",
                    ""type"": ""Button"",
                    ""id"": ""f2701b27-68a9-4351-947c-b1fe16b71fe3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num5"",
                    ""type"": ""Button"",
                    ""id"": ""b9c1121a-1192-4ae9-b3f1-5f9a4734116f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num6"",
                    ""type"": ""Button"",
                    ""id"": ""8413e9dc-fbe3-475d-945a-ca6795755be4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num7"",
                    ""type"": ""Button"",
                    ""id"": ""040083ec-a43f-41b1-b338-3a2137317eb0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num8"",
                    ""type"": ""Button"",
                    ""id"": ""4390de38-888d-48ee-b046-d76b805fc835"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num9"",
                    ""type"": ""Button"",
                    ""id"": ""d9d31ebe-c4cf-4804-b361-cf4906276f46"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""bad2dfce-f0c0-4864-8abf-613f4c0a22f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Delete"",
                    ""type"": ""Button"",
                    ""id"": ""221faa43-ba6e-40d1-b204-3bf12728c968"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dot"",
                    ""type"": ""Button"",
                    ""id"": ""39eb9eb3-d51f-48ca-891e-44870eaf4959"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""29dec4ca-6ab9-41c1-9a62-364035cf6811"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1b48c98-89bf-4468-80c3-2aebf4d06a70"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbc67b8a-b8f3-4410-bb8e-fffb540a45ea"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23bfadea-23eb-4382-bd1a-4f295397cce2"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37f99001-4769-4e7c-ba78-b448578f8ad5"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edc01c70-eb1e-4657-8b10-f4ea6b9db93a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e96e6de-8f19-42ee-8c18-b12608bb926d"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f47a7240-b060-43e1-88c3-b5ffe5a61fc3"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e30cf5a-fa6f-44b8-9035-a91451842373"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""939b6025-3163-44b2-b393-ff50ca5345b4"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63d066da-02c7-487d-afee-c97c438c97e0"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67ca6ea6-23a8-4f26-83a8-c1b2b35369b9"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d63769b-2fa2-48d1-ba0f-bf4559d37ecc"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3635dbfc-a8b7-4273-98d0-13d505ffc6cc"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cd7c376-d76d-4bc7-b93a-e8d31d0ee50b"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8789728e-7fb3-4647-98f4-d5cef53dfbab"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bfdf288-cc14-4a7f-a23d-af7b1337478d"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f715fe2-d87f-40ba-8bcd-fdacab59b73c"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c779b6e2-8d53-49bc-9e53-d8abbe6164d0"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f10743b4-3879-49a7-a061-6ea1c158be08"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Num9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e2fa09a-a7bd-463a-a370-012881ed9562"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""681f57cc-3842-4c3f-ba63-359e38e817b6"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f11fafe5-587b-4ce3-bce2-26545d312c0d"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bffe8bb-fea7-4cd6-91f5-99ca5dd30cee"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6559c50-3058-4481-88d2-e3940d3f4749"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""840ad57d-03ee-4a0c-bfee-c80ffed9bf9f"",
                    ""path"": ""<Keyboard>/numpadPeriod"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""5338b93c-460a-4ac2-a00a-cc62a8f59b9b"",
            ""actions"": [
                {
                    ""name"": ""OpenSettings"",
                    ""type"": ""Button"",
                    ""id"": ""5e70d51c-1602-4ac0-9b92-53954437849b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""KeyCombination"",
                    ""id"": ""42de7699-8503-4318-8aa4-d6da8183a41c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSettings"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""3eb73870-f4f7-4c9f-a380-377b4a9ac135"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSettings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""431abde4-745e-4c4a-88d8-bf65dbe78ceb"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSettings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Level1
        m_Level1 = asset.FindActionMap("Level1", throwIfNotFound: true);
        m_Level1_Movement = m_Level1.FindAction("Movement", throwIfNotFound: true);
        m_Level1_Collect = m_Level1.FindAction("Collect", throwIfNotFound: true);
        // Level2
        m_Level2 = asset.FindActionMap("Level2", throwIfNotFound: true);
        m_Level2_Num0 = m_Level2.FindAction("Num0", throwIfNotFound: true);
        m_Level2_Num1 = m_Level2.FindAction("Num1", throwIfNotFound: true);
        m_Level2_Num2 = m_Level2.FindAction("Num2", throwIfNotFound: true);
        m_Level2_Num3 = m_Level2.FindAction("Num3", throwIfNotFound: true);
        m_Level2_Num4 = m_Level2.FindAction("Num4", throwIfNotFound: true);
        m_Level2_Num5 = m_Level2.FindAction("Num5", throwIfNotFound: true);
        m_Level2_Num6 = m_Level2.FindAction("Num6", throwIfNotFound: true);
        m_Level2_Num7 = m_Level2.FindAction("Num7", throwIfNotFound: true);
        m_Level2_Num8 = m_Level2.FindAction("Num8", throwIfNotFound: true);
        m_Level2_Num9 = m_Level2.FindAction("Num9", throwIfNotFound: true);
        m_Level2_Submit = m_Level2.FindAction("Submit", throwIfNotFound: true);
        m_Level2_Delete = m_Level2.FindAction("Delete", throwIfNotFound: true);
        m_Level2_Dot = m_Level2.FindAction("Dot", throwIfNotFound: true);
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_OpenSettings = m_Menu.FindAction("OpenSettings", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Level1
    private readonly InputActionMap m_Level1;
    private List<ILevel1Actions> m_Level1ActionsCallbackInterfaces = new List<ILevel1Actions>();
    private readonly InputAction m_Level1_Movement;
    private readonly InputAction m_Level1_Collect;
    public struct Level1Actions
    {
        private @PlayerInputActions m_Wrapper;
        public Level1Actions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Level1_Movement;
        public InputAction @Collect => m_Wrapper.m_Level1_Collect;
        public InputActionMap Get() { return m_Wrapper.m_Level1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Level1Actions set) { return set.Get(); }
        public void AddCallbacks(ILevel1Actions instance)
        {
            if (instance == null || m_Wrapper.m_Level1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Level1ActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Collect.started += instance.OnCollect;
            @Collect.performed += instance.OnCollect;
            @Collect.canceled += instance.OnCollect;
        }

        private void UnregisterCallbacks(ILevel1Actions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Collect.started -= instance.OnCollect;
            @Collect.performed -= instance.OnCollect;
            @Collect.canceled -= instance.OnCollect;
        }

        public void RemoveCallbacks(ILevel1Actions instance)
        {
            if (m_Wrapper.m_Level1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILevel1Actions instance)
        {
            foreach (var item in m_Wrapper.m_Level1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Level1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Level1Actions @Level1 => new Level1Actions(this);

    // Level2
    private readonly InputActionMap m_Level2;
    private List<ILevel2Actions> m_Level2ActionsCallbackInterfaces = new List<ILevel2Actions>();
    private readonly InputAction m_Level2_Num0;
    private readonly InputAction m_Level2_Num1;
    private readonly InputAction m_Level2_Num2;
    private readonly InputAction m_Level2_Num3;
    private readonly InputAction m_Level2_Num4;
    private readonly InputAction m_Level2_Num5;
    private readonly InputAction m_Level2_Num6;
    private readonly InputAction m_Level2_Num7;
    private readonly InputAction m_Level2_Num8;
    private readonly InputAction m_Level2_Num9;
    private readonly InputAction m_Level2_Submit;
    private readonly InputAction m_Level2_Delete;
    private readonly InputAction m_Level2_Dot;
    public struct Level2Actions
    {
        private @PlayerInputActions m_Wrapper;
        public Level2Actions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Num0 => m_Wrapper.m_Level2_Num0;
        public InputAction @Num1 => m_Wrapper.m_Level2_Num1;
        public InputAction @Num2 => m_Wrapper.m_Level2_Num2;
        public InputAction @Num3 => m_Wrapper.m_Level2_Num3;
        public InputAction @Num4 => m_Wrapper.m_Level2_Num4;
        public InputAction @Num5 => m_Wrapper.m_Level2_Num5;
        public InputAction @Num6 => m_Wrapper.m_Level2_Num6;
        public InputAction @Num7 => m_Wrapper.m_Level2_Num7;
        public InputAction @Num8 => m_Wrapper.m_Level2_Num8;
        public InputAction @Num9 => m_Wrapper.m_Level2_Num9;
        public InputAction @Submit => m_Wrapper.m_Level2_Submit;
        public InputAction @Delete => m_Wrapper.m_Level2_Delete;
        public InputAction @Dot => m_Wrapper.m_Level2_Dot;
        public InputActionMap Get() { return m_Wrapper.m_Level2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Level2Actions set) { return set.Get(); }
        public void AddCallbacks(ILevel2Actions instance)
        {
            if (instance == null || m_Wrapper.m_Level2ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Level2ActionsCallbackInterfaces.Add(instance);
            @Num0.started += instance.OnNum0;
            @Num0.performed += instance.OnNum0;
            @Num0.canceled += instance.OnNum0;
            @Num1.started += instance.OnNum1;
            @Num1.performed += instance.OnNum1;
            @Num1.canceled += instance.OnNum1;
            @Num2.started += instance.OnNum2;
            @Num2.performed += instance.OnNum2;
            @Num2.canceled += instance.OnNum2;
            @Num3.started += instance.OnNum3;
            @Num3.performed += instance.OnNum3;
            @Num3.canceled += instance.OnNum3;
            @Num4.started += instance.OnNum4;
            @Num4.performed += instance.OnNum4;
            @Num4.canceled += instance.OnNum4;
            @Num5.started += instance.OnNum5;
            @Num5.performed += instance.OnNum5;
            @Num5.canceled += instance.OnNum5;
            @Num6.started += instance.OnNum6;
            @Num6.performed += instance.OnNum6;
            @Num6.canceled += instance.OnNum6;
            @Num7.started += instance.OnNum7;
            @Num7.performed += instance.OnNum7;
            @Num7.canceled += instance.OnNum7;
            @Num8.started += instance.OnNum8;
            @Num8.performed += instance.OnNum8;
            @Num8.canceled += instance.OnNum8;
            @Num9.started += instance.OnNum9;
            @Num9.performed += instance.OnNum9;
            @Num9.canceled += instance.OnNum9;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
            @Delete.started += instance.OnDelete;
            @Delete.performed += instance.OnDelete;
            @Delete.canceled += instance.OnDelete;
            @Dot.started += instance.OnDot;
            @Dot.performed += instance.OnDot;
            @Dot.canceled += instance.OnDot;
        }

        private void UnregisterCallbacks(ILevel2Actions instance)
        {
            @Num0.started -= instance.OnNum0;
            @Num0.performed -= instance.OnNum0;
            @Num0.canceled -= instance.OnNum0;
            @Num1.started -= instance.OnNum1;
            @Num1.performed -= instance.OnNum1;
            @Num1.canceled -= instance.OnNum1;
            @Num2.started -= instance.OnNum2;
            @Num2.performed -= instance.OnNum2;
            @Num2.canceled -= instance.OnNum2;
            @Num3.started -= instance.OnNum3;
            @Num3.performed -= instance.OnNum3;
            @Num3.canceled -= instance.OnNum3;
            @Num4.started -= instance.OnNum4;
            @Num4.performed -= instance.OnNum4;
            @Num4.canceled -= instance.OnNum4;
            @Num5.started -= instance.OnNum5;
            @Num5.performed -= instance.OnNum5;
            @Num5.canceled -= instance.OnNum5;
            @Num6.started -= instance.OnNum6;
            @Num6.performed -= instance.OnNum6;
            @Num6.canceled -= instance.OnNum6;
            @Num7.started -= instance.OnNum7;
            @Num7.performed -= instance.OnNum7;
            @Num7.canceled -= instance.OnNum7;
            @Num8.started -= instance.OnNum8;
            @Num8.performed -= instance.OnNum8;
            @Num8.canceled -= instance.OnNum8;
            @Num9.started -= instance.OnNum9;
            @Num9.performed -= instance.OnNum9;
            @Num9.canceled -= instance.OnNum9;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
            @Delete.started -= instance.OnDelete;
            @Delete.performed -= instance.OnDelete;
            @Delete.canceled -= instance.OnDelete;
            @Dot.started -= instance.OnDot;
            @Dot.performed -= instance.OnDot;
            @Dot.canceled -= instance.OnDot;
        }

        public void RemoveCallbacks(ILevel2Actions instance)
        {
            if (m_Wrapper.m_Level2ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILevel2Actions instance)
        {
            foreach (var item in m_Wrapper.m_Level2ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Level2ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Level2Actions @Level2 => new Level2Actions(this);

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    private readonly InputAction m_Menu_OpenSettings;
    public struct MenuActions
    {
        private @PlayerInputActions m_Wrapper;
        public MenuActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenSettings => m_Wrapper.m_Menu_OpenSettings;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
            @OpenSettings.started += instance.OnOpenSettings;
            @OpenSettings.performed += instance.OnOpenSettings;
            @OpenSettings.canceled += instance.OnOpenSettings;
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
            @OpenSettings.started -= instance.OnOpenSettings;
            @OpenSettings.performed -= instance.OnOpenSettings;
            @OpenSettings.canceled -= instance.OnOpenSettings;
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);
    public interface ILevel1Actions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCollect(InputAction.CallbackContext context);
    }
    public interface ILevel2Actions
    {
        void OnNum0(InputAction.CallbackContext context);
        void OnNum1(InputAction.CallbackContext context);
        void OnNum2(InputAction.CallbackContext context);
        void OnNum3(InputAction.CallbackContext context);
        void OnNum4(InputAction.CallbackContext context);
        void OnNum5(InputAction.CallbackContext context);
        void OnNum6(InputAction.CallbackContext context);
        void OnNum7(InputAction.CallbackContext context);
        void OnNum8(InputAction.CallbackContext context);
        void OnNum9(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnDelete(InputAction.CallbackContext context);
        void OnDot(InputAction.CallbackContext context);
    }
    public interface IMenuActions
    {
        void OnOpenSettings(InputAction.CallbackContext context);
    }
}
